apiVersion: apps/v1
kind: Deployment
metadata:
  name: martinafernandez-deployment
  labels:
    app: martinafernandez
spec:
  replicas: 1
  selector:
    matchLabels:
      app: martinafernandez
  template:
    metadata:
      labels:
        app: martinafernandez
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: martinafernandez
          image: ghcr.io/lucasmaraz/martinafernandez:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002